### ISSUE TITLE
Build OpenShift Environment For Development, Testing and Collaboration of Workshop Material

### ISSUE THREAD

**Issue by nickschuetz** [RedHatWorkshops/dil-cloudnative#25]
We need an environment where we as a group can develop, test and collaborate workloads and material that will live in OpenShift for the Day in the Life of a Cloud Native Team workshop(s). 

- The environment must be stable.
- The environment must have dynamic persistent storage.
- The environment must be able to handle the load of the entire cloud native team.
- The environment must be able to access the internet and be accessible from the internet.
- Bonus: The environment must be able to handle what we consider a standard workshop for testing and simulation.

**Comment by christianh814** [comment]
Has this env been provisioned? I need an environment with lots of activity for my monitoring workshop

Maybe we can benefit from our common need?

**Comment by justaugustus** [comment]
@nickschuetz / @christianh814 -- do we have any additional requirements e.g., HA install?

I can work this as part of the effort here: https://github.com/openshift-tigerteam/openshift-tf/pull/1

...but it wouldn't be until next week.

**Comment by christianh814** [comment]
I was thinking of building an HA cluster on AWS...I can create accounts for you guys to use. Or do you need 3 env? @nickschuetz

**Comment by justaugustus** [comment]
@christianh814 if you've got it in hand, then perfect. Work with @nickschuetz to get requirements and we can share envs! :)

**Comment by nickschuetz** [comment]
@christianh814 for the sake of time, please do incorporate us into your environment. Thanks. We just need to make sure it's stable and available until our Oct. deadline.

**Comment by christianh814** [comment]
@nickschuetz @justaugustus 

I've set up an env and sent you the info in an email. I'll let you guys review functionality before I close this.

**Comment by nickschuetz** [comment]
Looks good. Moving issue to Done.
