### ISSUE TITLE
Create Instructor Repo

### ISSUE THREAD

**Issue by justaugustus** [RedHatWorkshops/dil-cloudnative#4]
- Can maybe just use the existing dil-cloudnative repo for this.
- Purpose of this repo is to have all of the materials/instructions/notes for the instructor to setup/deliver the lab.
- Should include git submodules for each of the student repos so that we can easily reference and clone everything down at once.

**Comment by joshdreagan** [comment]
Agreed. We'll just use this repo as the instructor repo.
